version: '3'
services:
  no-name-mysql:
    image: mysql:5.7.36
    container_name: no-name-mysql
    platform: linux/amd64
    #    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "no_name_phpmyadmin"
    platform: linux/amd64
    #    restart: always
    environment:
      PMA_HOST: no-name-mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - no-name-mysql


  no-name:
    build: .
    container_name: "no-name"
    platform: linux/amd64
    ports:
      - 8080:8080
    links:
      - no-name-mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://no-name-mysql:3306/test_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - no-name-mysql