version: '3'
services:
  no-name-mysql:
    image: mysql:5.7.36
    container_name: no-name-mysql
    platform: linux/amd64
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      -  $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "no_name_phpmyadmin"
    platform: linux/amd64
    environment:
      PMA_HOST: no-name-mysql
      PMA_USER: $MYSQLDB_USER
      PMA_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    ports:
      - $PHPMYADMIN_LOCAL_PORT:$PHPMYADMIN_DOCKER_PORT
    depends_on:
      - no-name-mysql